// Code generated by simdjson/tools/structgen. DO NOT EDIT.

package gentest

import (
	"unsafe"

	"github.com/sebishogun/simdjson"
)

func init() {
	simdjson.RegisterEncoder[Outer](encodeOuter)
}

func encodeInner(dst []byte, p unsafe.Pointer, o simdjson.Options) []byte {
	v := (*Inner)(p)
	_ = v
	dst = append(dst, "{\"n\":"...)
	dst = simdjson.AppendInt(dst, int64(v.N))
	dst = append(dst, ",\"s\":"...)
	dst = simdjson.AppendString(dst, v.S, o)
	return append(dst, '}')
}

func encodeOuter(dst []byte, p unsafe.Pointer, o simdjson.Options) []byte {
	v := (*Outer)(p)
	_ = v
	dst = append(dst, "{\"id\":"...)
	dst = simdjson.AppendInt(dst, int64(v.ID))
	dst = append(dst, ",\"name\":"...)
	dst = simdjson.AppendString(dst, v.Name, o)
	dst = append(dst, ",\"ok\":"...)
	dst = simdjson.AppendBool(dst, v.Ok)
	dst = append(dst, ",\"ratio\":"...)
	dst = simdjson.AppendFloat(dst, v.Ratio, 64)
	dst = append(dst, ",\"small\":"...)
	dst = simdjson.AppendInt(dst, int64(v.Small))
	dst = append(dst, ",\"u\":"...)
	dst = simdjson.AppendUint(dst, uint64(v.U))
	dst = append(dst, ",\"kid\":"...)
	dst = encodeInner(dst, unsafe.Pointer(&v.Kid), o)
	dst = append(dst, ",\"kids\":"...)
	if v.Kids == nil {
		dst = append(dst, "null"...)
	} else {
		dst = append(dst, '[')
		for i := range v.Kids {
			if i > 0 {
				dst = append(dst, ',')
			}
			dst = encodeInner(dst, unsafe.Pointer(&v.Kids[i]), o)
		}
		dst = append(dst, ']')
	}
	dst = append(dst, ",\"words\":"...)
	if v.Words == nil {
		dst = append(dst, "null"...)
	} else {
		dst = append(dst, '[')
		for i := range v.Words {
			if i > 0 {
				dst = append(dst, ',')
			}
			dst = simdjson.AppendString(dst, v.Words[i], o)
		}
		dst = append(dst, ']')
	}
	return append(dst, '}')
}
