// Package gentest is the fixture structgen is exercised against.
//
// The generated encoder in this directory is committed and regenerated by
// TestGeneratedFileIsCurrent, so a change to the generator that alters its
// output fails a test rather than going unnoticed until someone regenerates.
package gentest

//go:generate sh -c "cd ../../tools && go run ./structgen -dir $(pwd)/../internal/gentest -types Outer"

type Inner struct {
	N int    `json:"n"`
	S string `json:"s"`
}

type Outer struct {
	ID      int64    `json:"id"`
	Name    string   `json:"name"`
	Ok      bool     `json:"ok"`
	Ratio   float64  `json:"ratio"`
	Small   int32    `json:"small"`
	U       uint16   `json:"u"`
	Kid     Inner    `json:"kid"`
	Kids    []Inner  `json:"kids"`
	Words   []string `json:"words"`
	Skipped string   `json:"-"`
	hidden  int
}

// Plain is Outer with no encoder registered, so Marshal compiles a reflect
// encoder for it. Same fields, same tags, same order, so its output is exactly
// what the generated encoder has to match.
type Plain struct {
	ID      int64    `json:"id"`
	Name    string   `json:"name"`
	Ok      bool     `json:"ok"`
	Ratio   float64  `json:"ratio"`
	Small   int32    `json:"small"`
	U       uint16   `json:"u"`
	Kid     Inner    `json:"kid"`
	Kids    []Inner  `json:"kids"`
	Words   []string `json:"words"`
	Skipped string   `json:"-"`
	hidden  int
}

// Declined is here to be refused. Every field is a shape structgen does not
// implement, and the test asserts it declines rather than guessing.
type Declined struct {
	M   map[string]int `json:"m"`
	P   *Inner         `json:"p"`
	Any any            `json:"any"`
	Omi string         `json:"omi,omitempty"`
	B   []byte         `json:"b"`
}
