// Command genpow10 emits float_pow10_gen.go: the 128-bit normalized powers of
// ten the Eisel-Lemire path multiplies against, 10^-342 through 10^308.
//
// Each power is the 128-bit mantissa of 10^q normalized to [2^127, 2^128).
// For q >= 0 the exact value is truncated to 128 bits; for q < 0 the
// reciprocal is rounded UP (ceil), which is the construction the algorithm's
// truncation-ambiguity check is stated against. Both cases are computed
// exactly with math/big; nothing here is floating point.
package main

import (
	"fmt"
	"math/big"
	"os"
)

func main() {
	var out []byte
	app := func(s string, a ...any) { out = append(out, fmt.Sprintf(s, a...)...) }
	app("// Code generated by tools/genpow10. DO NOT EDIT.\n\n")
	app("package simdjson\n\n")
	app("// lemire10Min and lemire10Max bound the decimal exponents the table covers.\n")
	app("const lemire10Min, lemire10Max = -342, 308\n\n")
	app("// lemire10Tab holds, for each q in [lemire10Min, lemire10Max], the 128-bit\n")
	app("// mantissa of 10^q normalized to [2^127, 2^128), as {hi, lo}.\n")
	app("var lemire10Tab = [...][2]uint64{\n")

	one28 := new(big.Int).Lsh(big.NewInt(1), 128)
	one27 := new(big.Int).Lsh(big.NewInt(1), 127)
	for q := -342; q <= 308; q++ {
		m := new(big.Int)
		if q >= 0 {
			// 10^q, truncated into [2^127, 2^128).
			m.Exp(big.NewInt(10), big.NewInt(int64(q)), nil)
			for m.Cmp(one28) >= 0 {
				m.Rsh(m, 1)
			}
			for m.Cmp(one27) < 0 {
				m.Lsh(m, 1)
			}
		} else {
			// ceil(2^k / 10^-q) for the k that lands in [2^127, 2^128).
			den := new(big.Int).Exp(big.NewInt(10), big.NewInt(int64(-q)), nil)
			k := uint(127 + den.BitLen())
			for {
				num := new(big.Int).Lsh(big.NewInt(1), k)
				quo, rem := new(big.Int).QuoRem(num, den, new(big.Int))
				if rem.Sign() != 0 {
					quo.Add(quo, big.NewInt(1))
				}
				if quo.Cmp(one27) >= 0 && quo.Cmp(one28) < 0 {
					m = quo
					break
				}
				if quo.Cmp(one28) >= 0 {
					k--
				} else {
					k++
				}
			}
		}
		lo := new(big.Int).And(m, new(big.Int).SetUint64(^uint64(0)))
		hi := new(big.Int).Rsh(m, 64)
		app("\t{0x%016x, 0x%016x}, // 1e%d\n", hi.Uint64(), lo.Uint64(), q)
	}
	app("}\n")
	path := "float_pow10_gen.go"
	if len(os.Args) > 1 {
		path = os.Args[1]
	}
	if err := os.WriteFile(path, out, 0o644); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
